SHOW_HZ_HACK?=0
ifeq (1,$(strip ${SHOW_HZ_HACK}))
obj-m := SHOW_HZ.o
ccflags-y += -save-temps=obj
else
obj-m := sch_jens.o sch_jhtb.o
#ccflags-y += -fverbose-asm -save-temps=obj
endif

# work around stable kernel API+ABI breakage
ifeq (4,$(strip ${VERSION}))
ifeq (19,$(strip ${PATCHLEVEL}))
ccflags-y += -DJENS_LINUX_4_19_SL=$(strip ${SUBLEVEL})
endif
endif
