SHOW_HZ_HACK?=0
ifeq (1,$(strip ${SHOW_HZ_HACK}))
obj-m := SHOW_HZ.o
ccflags-y += -save-temps=obj
else
obj-m := sch_janz.o sch_janzdbg.o sch_multijens.o
obj-m += sch_jensvq2proto.o sch_jensvq3proto.o sch_jensvq4proto.o sch_jensvq5proto.o
obj-m += sch_jensvq2pvqd.o sch_jensvq3pvqd.o sch_jensvq4pvqd.o sch_jensvq5pvqd.o
#ccflags-y += -fverbose-asm -save-temps=obj
endif

# work around Linux adding flags it itself isn’t even ready for
ccflags-y += -Wimplicit-fallthrough=4

# aaaaaaaaaaaaaaaah! Why U disable these Loonix?!
ccflags-y += -Wformat-security -Wunused-but-set-variable -Wunused-const-variable -Wmaybe-uninitialized
