SHOW_HZ_HACK?=0
ifeq (1,$(strip ${SHOW_HZ_HACK}))
obj-m := SHOW_HZ.o
ccflags-y += -save-temps=obj
else
obj-m := sch_janz.o sch_janzdbg.o sch_multijens.o
#ccflags-y += -fverbose-asm -save-temps=obj
endif

# work around Linux adding flags it itself isn’t even ready for
ccflags-y += -Wimplicit-fallthrough=4
